[project]
name = "meeting-briefing-agent"
version = "0.1.0"
description = "Meeting Briefing Agent - compiles comprehensive meeting preparation briefings"
requires-python = ">=3.12"
dependencies = [
    "genai-protocol>=1.0.9",
    "python-dotenv>=1.1.0",
    "google-generativeai>=0.8.0",
]
